### ISSUE TITLE
Unable to build on Ubuntu Xenial

### ISSUE THREAD

**Issue by 6A** [nim-lang/nimble#406]
Building nimble does not work on Ubuntu 16.2.

Building Nimble using `koch tools`, `koch nimble` and `bin/nim c --noNimblePath -p:compiler -o:./bin/nimble dist/nimble/src/nimble.nim` fails with the following error:

```
Hint:  [Link]
dist/nimble/src/nimcache/stdlib_Uri.o: In function `dollar__x3qq8dnThSMcb3IWnRvBdg':
stdlib_Uri.c:(.text+0x99): multiple definition of `dollar__x3qq8dnThSMcb3IWnRvBdg'
dist/nimble/src/nimcache/stdlib_uri.o:stdlib_Uri.c:(.text+0x99): first defined here
dist/nimble/src/nimcache/stdlib_Uri.o: In function `slash__VB00WakXgdQwbimHgDgJ8Q':
stdlib_Uri.c:(.text+0x22e): multiple definition of `slash__VB00WakXgdQwbimHgDgJ8Q'
dist/nimble/src/nimcache/stdlib_uri.o:stdlib_Uri.c:(.text+0x22e): first defined here
dist/nimble/src/nimcache/stdlib_Uri.o: In function `add_TC4c9bvLgOei3Z0BlLrykVQ':
stdlib_Uri.c:(.text+0x499): multiple definition of `add_TC4c9bvLgOei3Z0BlLrykVQ'
dist/nimble/src/nimcache/stdlib_uri.o:stdlib_Uri.c:(.text+0x499): first defined here
dist/nimble/src/nimcache/stdlib_Uri.o: In function `parseAuthority_13OJZSBWQWBhOImtSUeepw':
stdlib_Uri.c:(.text+0x5a3): multiple definition of `parseAuthority_13OJZSBWQWBhOImtSUeepw'
dist/nimble/src/nimcache/stdlib_uri.o:stdlib_Uri.c:(.text+0x5a3): first defined here
dist/nimble/src/nimcache/stdlib_Uri.o: In function `parsePath_uBxgv9cVVt9cSi323e6Tyklg':
stdlib_Uri.c:(.text+0xbca): multiple definition of `parsePath_uBxgv9cVVt9cSi323e6Tyklg'
dist/nimble/src/nimcache/stdlib_uri.o:stdlib_Uri.c:(.text+0xbca): first defined here
dist/nimble/src/nimcache/stdlib_Uri.o: In function `initUri_XsAAWhfZwfutRcPKqP0nPw':
stdlib_Uri.c:(.text+0xf4e): multiple definition of `initUri_XsAAWhfZwfutRcPKqP0nPw'
dist/nimble/src/nimcache/stdlib_uri.o:stdlib_Uri.c:(.text+0xf4e): first defined here
dist/nimble/src/nimcache/stdlib_Uri.o: In function `resetUri_hLxZht05b29btFQtC2JxCDA':
stdlib_Uri.c:(.text+0x107c): multiple definition of `resetUri_hLxZht05b29btFQtC2JxCDA'
dist/nimble/src/nimcache/stdlib_uri.o:stdlib_Uri.c:(.text+0x107c): first defined here
dist/nimble/src/nimcache/stdlib_Uri.o: In function `parseUri_tik351FEDEGAc4bXBdtopQ':
stdlib_Uri.c:(.text+0x17f7): multiple definition of `parseUri_tik351FEDEGAc4bXBdtopQ'
dist/nimble/src/nimcache/stdlib_uri.o:stdlib_Uri.c:(.text+0x17f7): first defined here
dist/nimble/src/nimcache/stdlib_Uri.o: In function `parseUri_vimVCxGBr1pZ35g63f39b6Q':
stdlib_Uri.c:(.text+0x1e91): multiple definition of `parseUri_vimVCxGBr1pZ35g63f39b6Q'
dist/nimble/src/nimcache/stdlib_uri.o:stdlib_Uri.c:(.text+0x1e91): first defined here
dist/nimble/src/nimcache/stdlib_Uri.o: In function `removeDotSegments_KVvr4Rg8zV23InumJ3X12w':
stdlib_Uri.c:(.text+0x210a): multiple definition of `removeDotSegments_KVvr4Rg8zV23InumJ3X12w'
dist/nimble/src/nimcache/stdlib_uri.o:stdlib_Uri.c:(.text+0x210a): first defined here
dist/nimble/src/nimcache/stdlib_Uri.o: In function `merge_otr0YPtcweWgdOl4jWigsg':
stdlib_Uri.c:(.text+0x2a49): multiple definition of `merge_otr0YPtcweWgdOl4jWigsg'
dist/nimble/src/nimcache/stdlib_uri.o:stdlib_Uri.c:(.text+0x2a49): first defined here
dist/nimble/src/nimcache/stdlib_Uri.o: In function `combine_9acBZNRsrxKWWK9agATZh9b9bQ':
stdlib_Uri.c:(.text+0x2dc1): multiple definition of `combine_9acBZNRsrxKWWK9agATZh9b9bQ'
dist/nimble/src/nimcache/stdlib_uri.o:stdlib_Uri.c:(.text+0x2dc1): first defined here
dist/nimble/src/nimcache/stdlib_Uri.o: In function `combine_ncA9crzMvNMOfWDSJRVr82g':
stdlib_Uri.c:(.text+0x3472): multiple definition of `combine_ncA9crzMvNMOfWDSJRVr82g'
dist/nimble/src/nimcache/stdlib_uri.o:stdlib_Uri.c:(.text+0x3472): first defined here
dist/nimble/src/nimcache/stdlib_Uri.o: In function `isAbsolute_4o0bZBAllaOONbLEPKWQkg':
stdlib_Uri.c:(.text+0x3693): multiple definition of `isAbsolute_4o0bZBAllaOONbLEPKWQkg'
dist/nimble/src/nimcache/stdlib_uri.o:stdlib_Uri.c:(.text+0x3693): first defined here
dist/nimble/src/nimcache/stdlib_Uri.o: In function `slash__nlQH3LiIA676nOlLtlobtA':
stdlib_Uri.c:(.text+0x381a): multiple definition of `slash__nlQH3LiIA676nOlLtlobtA'
dist/nimble/src/nimcache/stdlib_uri.o:stdlib_Uri.c:(.text+0x381a): first defined here
dist/nimble/src/nimcache/stdlib_Uri.o: In function `dollar__cNNACCGXi9b0oYWhiTKNWww':
stdlib_Uri.c:(.text+0x3b7c): multiple definition of `dollar__cNNACCGXi9b0oYWhiTKNWww'
dist/nimble/src/nimcache/stdlib_uri.o:stdlib_Uri.c:(.text+0x3b7c): first defined here
dist/nimble/src/nimcache/stdlib_Uri.o: In function `stdlib_UriInit000':
stdlib_Uri.c:(.text+0x4133): multiple definition of `stdlib_UriInit000'
dist/nimble/src/nimcache/stdlib_uri.o:stdlib_Uri.c:(.text+0x4133): first defined here
dist/nimble/src/nimcache/stdlib_Uri.o: In function `stdlib_UriDatInit000':
stdlib_Uri.c:(.text+0x4190): multiple definition of `stdlib_UriDatInit000'
dist/nimble/src/nimcache/stdlib_uri.o:stdlib_Uri.c:(.text+0x4190): first defined here
dist/nimble/src/nimcache/nimble_nimble.o: In function `develop_Nylx3M8pmcbTsc3Rkl5Bxg_12':
nimble_nimble.c:(.text+0x1462c): undefined reference to `parseUri_HN0Rsm1KKAfXov53XGF88Q'
dist/nimble/src/nimcache/nimble_nimble.o: In function `PreMainInner':
nimble_nimble.c:(.text+0x16a26): undefined reference to `stdlib_uriDatInit000'
nimble_nimble.c:(.text+0x16d37): undefined reference to `stdlib_uriInit000'
dist/nimble/src/nimcache/stdlib_httpclient.o: In function `newProxy_hbzgaYRDEVdeOKRBZVbI4Q':
stdlib_httpclient.c:(.text+0x3606): undefined reference to `parseUri_HN0Rsm1KKAfXov53XGF88Q'
dist/nimble/src/nimcache/stdlib_httpclient.o: In function `request_PoEFzQsN5oDrulcNoUppqQ':
stdlib_httpclient.c:(.text+0x50bc): undefined reference to `parseUri_HN0Rsm1KKAfXov53XGF88Q'
stdlib_httpclient.c:(.text+0x50d2): undefined reference to `NTI_j49bukNPrq747O1GRd4Ng9bQ_'
stdlib_httpclient.c:(.text+0x5129): undefined reference to `NTI_j49bukNPrq747O1GRd4Ng9bQ_'
stdlib_httpclient.c:(.text+0x5178): undefined reference to `parseUri_HN0Rsm1KKAfXov53XGF88Q'
dist/nimble/src/nimcache/stdlib_httpclient.o: In function `getNewLocation_0pKC12yAY7Q7vtGqXF9bzzQ':
stdlib_httpclient.c:(.text+0x69ff): undefined reference to `parseUri_HN0Rsm1KKAfXov53XGF88Q'
stdlib_httpclient.c:(.text+0x6b19): undefined reference to `parseUri_HN0Rsm1KKAfXov53XGF88Q'
stdlib_httpclient.c:(.text+0x6bad): undefined reference to `dollar__Q6hX9cwycP8fRn52OpcLEjw'
dist/nimble/src/nimcache/stdlib_httpclient.o: In function `generateHeaders_AF4QwTQc21rZs6CVeWGmBg':
stdlib_httpclient.c:(.text+0x83d0): undefined reference to `NTI_j49bukNPrq747O1GRd4Ng9bQ_'
stdlib_httpclient.c:(.text+0x843e): undefined reference to `dollar__Q6hX9cwycP8fRn52OpcLEjw'
dist/nimble/src/nimcache/stdlib_httpclient.o: In function `newConnectionIter_P27hm9aL10ljKzLmYnFMsqA_7':
stdlib_httpclient.c:(.text+0x10984): undefined reference to `NTI_j49bukNPrq747O1GRd4Ng9bQ_'
dist/nimble/src/nimcache/stdlib_httpclient.o: In function `newConnection_VBu9csG0HRM7Z9altVpYbhzw':
stdlib_httpclient.c:(.text+0x10f41): undefined reference to `NTI_j49bukNPrq747O1GRd4Ng9bQ_'
dist/nimble/src/nimcache/stdlib_httpclient.o: In function `newConnection_QcmRKqRV3Rx4SrSAHcx9ckA':
stdlib_httpclient.c:(.text+0x11750): undefined reference to `NTI_j49bukNPrq747O1GRd4Ng9bQ_'
dist/nimble/src/nimcache/stdlib_httpclient.o: In function `requestAuxIter_P27hm9aL10ljKzLmYnFMsqA_8':
stdlib_httpclient.c:(.text+0x12239): undefined reference to `NTI_j49bukNPrq747O1GRd4Ng9bQ_'
stdlib_httpclient.c:(.text+0x12260): undefined reference to `parseUri_HN0Rsm1KKAfXov53XGF88Q'
stdlib_httpclient.c:(.text+0x12283): undefined reference to `NTI_j49bukNPrq747O1GRd4Ng9bQ_'
stdlib_httpclient.c:(.text+0x122bb): undefined reference to `NTI_j49bukNPrq747O1GRd4Ng9bQ_'
stdlib_httpclient.c:(.text+0x122e2): undefined reference to `parseUri_HN0Rsm1KKAfXov53XGF88Q'
stdlib_httpclient.c:(.text+0x123ac): undefined reference to `NTI_j49bukNPrq747O1GRd4Ng9bQ_'
stdlib_httpclient.c:(.text+0x123de): undefined reference to `NTI_j49bukNPrq747O1GRd4Ng9bQ_'
stdlib_httpclient.c:(.text+0x124b7): undefined reference to `dollar__Q6hX9cwycP8fRn52OpcLEjw'
dist/nimble/src/nimcache/stdlib_httpclient.o: In function `requestAux_AOtIL8rSE9aE49bGamB4vl8g':
stdlib_httpclient.c:(.text+0x135e5): undefined reference to `parseUri_HN0Rsm1KKAfXov53XGF88Q'
stdlib_httpclient.c:(.text+0x1367d): undefined reference to `parseUri_HN0Rsm1KKAfXov53XGF88Q'
stdlib_httpclient.c:(.text+0x1373c): undefined reference to `NTI_j49bukNPrq747O1GRd4Ng9bQ_'
stdlib_httpclient.c:(.text+0x13783): undefined reference to `NTI_j49bukNPrq747O1GRd4Ng9bQ_'
stdlib_httpclient.c:(.text+0x13803): undefined reference to `dollar__Q6hX9cwycP8fRn52OpcLEjw'
dist/nimble/src/nimcache/stdlib_httpclient.o: In function `stdlib_httpclientDatInit000':
stdlib_httpclient.c:(.text+0x1b52e): undefined reference to `NTI_j49bukNPrq747O1GRd4Ng9bQ_'
stdlib_httpclient.c:(.text+0x1b756): undefined reference to `NTI_j49bukNPrq747O1GRd4Ng9bQ_'
stdlib_httpclient.c:(.text+0x1bb9e): undefined reference to `NTI_j49bukNPrq747O1GRd4Ng9bQ_'
stdlib_httpclient.c:(.text+0x1d1e7): undefined reference to `NTI_j49bukNPrq747O1GRd4Ng9bQ_'
stdlib_httpclient.c:(.text+0x1d6f7): undefined reference to `NTI_j49bukNPrq747O1GRd4Ng9bQ_'
dist/nimble/src/nimcache/stdlib_httpclient.o:stdlib_httpclient.c:(.text+0x1d75d): more undefined references to `NTI_j49bukNPrq747O1GRd4Ng9bQ_' follow
dist/nimble/src/nimcache/nimble_tools.o: In function `getDownloadDirName_kGfQkaMN4AP407RuBq9baKQ':
nimble_tools.c:(.text+0x3166): undefined reference to `parseUri_HN0Rsm1KKAfXov53XGF88Q'
dist/nimble/src/nimcache/nimble_options.o: In function `getProxy_Q3N4ABv9acIMVMABdoTSJmQ':
nimble_options.c:(.text+0x4112): undefined reference to `parseUri_HN0Rsm1KKAfXov53XGF88Q'
nimble_options.c:(.text+0x424e): undefined reference to `parseUri_HN0Rsm1KKAfXov53XGF88Q'
nimble_options.c:(.text+0x436d): undefined reference to `dollar__Q6hX9cwycP8fRn52OpcLEjw'
dist/nimble/src/nimcache/nimble_publish.o: In function `publish_pXDlG2vyNWPtgLiu4Tvjcw':
nimble_publish.c:(.text+0x3ad1): undefined reference to `parseUri_HN0Rsm1KKAfXov53XGF88Q'
nimble_publish.c:(.text+0x3bc3): undefined reference to `parseUri_HN0Rsm1KKAfXov53XGF88Q'
collect2: error: ld returned 1 exit status
Error: execution of an external program failed: 'gcc   -o /root/nim-0.17.2/./bin/nimble  dist/nimble/src/nimcache/linenoise.o dist/nimble/src/nimcache/nimble_nimble.o dist/nimble/src/nimcache/stdlib_system.o dist/nimble/src/nimcache/stdlib_httpclient.o dist/nimble/src/nimcache/stdlib_net.o dist/nimble/src/nimcache/stdlib_strutils.o
dist/nimble/src/nimcache/stdlib_uri.o dist/nimble/src/nimcache/stdlib_parseutils.o dist/nimble/src/nimcache/stdlib_strtabs.o dist/nimble/src/nimcache/stdlib_base64.o dist/nimble/src/nimcache/stdlib_os.o dist/nimble/src/nimcache/stdlib_mimetypes.o dist/nimble/src/nimcache/stdlib_math.o dist/nimble/src/nimcache/stdlib_random.o
dist/nimble/src/nimcache/stdlib_httpcore.o dist/nimble/src/nimcache/stdlib_times.o
dist/nimble/src/nimcache/stdlib_tables.o dist/nimble/src/nimcache/stdlib_streams.o dist/nimble/src/nimcache/stdlib_nativesockets.o dist/nimble/src/nimcache/stdlib_options.o dist/nimble/src/nimcache/stdlib_algorithm.o dist/nimble/src/nimcache/stdlib_posix.o dist/nimble/src/nimcache/stdlib_ospaths.o dist/nimble/src/nimcache/stdlib_typetraits.o dist/nimble/src/nimcache/stdlib_sets.o dist/nimble/src/nimcache/stdlib_hashes.o dist/nimble/src/nimcache/stdlib_openssl.o dist/nimble/src/nimcache/stdlib_dynlib.o dist/nimble/src/nimcache/stdlib_asyncnet.o dist/nimble/src/nimcache/stdlib_asyncdispatch.o dist/nimble/src/nimcache/stdlib_heapqueue.o dist/nimble/src/nimcache/stdlib_asyncstreams.o dist/nimble/src/nimcache/stdlib_asyncfutures.o dist/nimble/src/nimcache/stdlib_deques.o dist/nimble/src/nimcache/stdlib_selectors.o dist/nimble/src/nimcache/stdlib_epoll.o dist/nimble/src/nimcache/stdlib_macros.o dist/nimble/src/nimcache/stdlib_asyncfile.o dist/nimble/src/nimcache/stdlib_parseopt.o dist/nimble/src/nimcache/stdlib_osproc.o dist/nimble/src/nimcache/stdlib_cpuinfo.o dist/nimble/src/nimcache/stdlib_linux.o dist/nimble/src/nimcache/stdlib_pegs.o dist/nimble/src/nimcache/stdlib_unicode.o dist/nimble/src/nimcache/stdlib_json.o dist/nimble/src/nimcache/stdlib_lexbase.o dist/nimble/src/nimcache/stdlib_future.o dist/nimble/src/nimcache/stdlib_sequtils.o dist/nimble/src/nimcache/nimble_packageinfo.o dist/nimble/src/nimcache/stdlib_parsecfg.o dist/nimble/src/nimcache/nimble_version.o dist/nimble/src/nimcache/nimble_tools.o dist/nimble/src/nimcache/nimble_common.o dist/nimble/src/nimcache/nimble_cli.o dist/nimble/src/nimcache/stdlib_logging.o dist/nimble/src/nimcache/stdlib_terminal.o dist/nimble/src/nimcache/stdlib_termios.o dist/nimble/src/nimcache/nimble_options.o dist/nimble/src/nimcache/nimble_config.o dist/nimble/src/nimcache/stdlib_Uri.o dist/nimble/src/nimcache/nimble_download.o dist/nimble/src/nimcache/nimble_packageparser.o dist/nimble/src/nimcache/nimble_nimscriptsupport.o dist/nimble/src/nimcache/compiler_ast.o dist/nimble/src/nimcache/compiler_modules.o dist/nimble/src/nimcache/compiler_passes.o dist/nimble/src/nimcache/compiler_passaux.o dist/nimble/src/nimcache/compiler_condsyms.o dist/nimble/src/nimcache/compiler_sem.o
dist/nimble/src/nimcache/compiler_semdata.o dist/nimble/src/nimcache/compiler_llstream.o dist/nimble/src/nimcache/compiler_vm.o dist/nimble/src/nimcache/compiler_vmdef.o dist/nimble/src/nimcache/compiler_commands.o dist/nimble/src/nimcache/compiler_msgs.o dist/nimble/src/nimcache/compiler_magicsys.o dist/nimble/src/nimcache/compiler_idents.o dist/nimble/src/nimcache/compiler_nimconf.o dist/nimble/src/nimcache/compiler_nversion.o dist/nimble/src/nimcache/compiler_options.o dist/nimble/src/nimcache/stdlib_securehash.o dist/nimble/src/nimcache/compiler_ropes.o dist/nimble/src/nimcache/stdlib_intsets.o dist/nimble/src/nimcache/compiler_idgen.o dist/nimble/src/nimcache/compiler_platform.o dist/nimble/src/nimcache/compiler_wordrecg.o dist/nimble/src/nimcache/compiler_astalgo.o dist/nimble/src/nimcache/compiler_rodread.o dist/nimble/src/nimcache/compiler_cgendata.o dist/nimble/src/nimcache/compiler_sigmatch.o dist/nimble/src/nimcache/compiler_lexer.o dist/nimble/src/nimcache/compiler_syntaxes.o dist/nimble/src/nimcache/compiler_modulegraphs.o dist/nimble/src/nimcache/compiler_rodutils.o dist/nimble/src/nimcache/compiler_types.o dist/nimble/src/nimcache/stdlib_memfiles.o dist/nimble/src/nimcache/compiler_tres.o dist/nimble/src/nimcache/compiler_renderer.o dist/nimble/src/nimcache/compiler_nimlexbase.o dist/nimble/src/nimcache/compiler_sighashes.o dist/nimble/src/nimcache/compiler_ndi.o dist/nimble/src/nimcache/compiler_extccomp.o dist/nimble/src/nimcache/compiler_nimsets.o dist/nimble/src/nimcache/compiler_reorder.o dist/nimble/src/nimcache/compiler_bitsets.o dist/nimble/src/nimcache/compiler_parser.o dist/nimble/src/nimcache/compiler_pbraces.o dist/nimble/src/nimcache/compiler_filters.o dist/nimble/src/nimcache/compiler_filter_tmpl.o dist/nimble/src/nimcache/stdlib_md5.o dist/nimble/src/nimcache/compiler_lookups.o dist/nimble/src/nimcache/compiler_semtypinst.o
dist/nimble/src/nimcache/compiler_parampatterns.o dist/nimble/src/nimcache/compiler_pretty.o dist/nimble/src/nimcache/compiler_treetab.o dist/nimble/src/nimcache/compiler_prettybase.o dist/nimble/src/nimcache/compiler_docgen.o dist/nimble/src/nimcache/docutils_rstast.o dist/nimble/src/nimcache/docutils_rst.o dist/nimble/src/nimcache/docutils_rstgen.o dist/nimble/src/nimcache/docutils_highlite.o dist/nimble/src/nimcache/compiler_importer.o dist/nimble/src/nimcache/compiler_sempass2.o dist/nimble/src/nimcache/stdlib_xmltree.o dist/nimble/src/nimcache/stdlib_cgi.o dist/nimble/src/nimcache/compiler_typesrenderer.o dist/nimble/src/nimcache/compiler_guards.o dist/nimble/src/nimcache/compiler_writetracking.o dist/nimble/src/nimcache/compiler_saturate.o dist/nimble/src/nimcache/stdlib_cookies.o dist/nimble/src/nimcache/compiler_prefixmatches.o dist/nimble/src/nimcache/compiler_semfold.o dist/nimble/src/nimcache/compiler_procfind.o dist/nimble/src/nimcache/compiler_pragmas.o dist/nimble/src/nimcache/compiler_transf.o dist/nimble/src/nimcache/compiler_aliases.o dist/nimble/src/nimcache/compiler_cgmeth.o dist/nimble/src/nimcache/compiler_lambdalifting.o dist/nimble/src/nimcache/compiler_evaltempl.o dist/nimble/src/nimcache/compiler_patterns.o dist/nimble/src/nimcache/compiler_semmacrosanity.o dist/nimble/src/nimcache/compiler_semparallel.o dist/nimble/src/nimcache/compiler_lowerings.o dist/nimble/src/nimcache/compiler_pluginsupport.o dist/nimble/src/nimcache/compiler_active.o dist/nimble/src/nimcache/compiler_nimblecmd.o dist/nimble/src/nimcache/compiler_vmgen.o dist/nimble/src/nimcache/compiler_vmdeps.o dist/nimble/src/nimcache/compiler_vmmarshal.o dist/nimble/src/nimcache/compiler_locals.o dist/nimble/src/nimcache/compiler_itersgen.o dist/nimble/src/nimcache/compiler_scriptconfig.o dist/nimble/src/nimcache/nimble_publish.o dist/nimble/src/nimcache/stdlib_rdstdin.o dist/nimble/src/nimcache/stdlib_linenoise.o dist/nimble/src/nimcache/stdlib_browsers.o dist/nimble/src/nimcache/nimble_packageinstaller.o dist/nimble/src/nimcache/nimble_reversedeps.o dist/nimble/src/nimcache/nimble_nimscriptexecutor.o  -lm -lrt   -ldl'
```

I tried with `nim-0.17.0`, `nim-0.17.2`, `gcc-5.4.0`, `gcc-7.2.0`, `nimble@master` and `nimble@stable`. Same result in every case.

**Comment by dom96** [comment]
Can you build other things using Nim?

Whatever the answer, you might wish to install Nim using [``choosenim``](https://github.com/dom96/choosenim).

**Comment by 6A** [comment]
Yes, the other tools (`nimsuggest`, for example) were built without a problem.

Using `choosenim`, `nimsuggest` also cannot be build, and outputs an error similar to the one shown above for `nimble`.

**Comment by Calinou** [comment]
You could try using Clang ([Ubuntu 16.04 has version 3.8 in the repositories](https://packages.ubuntu.com/xenial/clang)) instead of GCC. You can change the compiler used by Nim by editing the `cc` variable definition in `config/nim.cfg`, replacing `gcc` with `clang`.

**Comment by dom96** [comment]
But presumably ``choosenim`` was able to build ``nimble`` successfully?

Try removing the nimcache or just use the Nimble built by ``choosenim``. If you're still running into this it might be a good idea to pop into IRC or the forum to ask. I don't think this is a Nimble-specific problem so I'll close this.
